# Generated by Django 3.2.5 on 2021-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clickup_pk',
            field=models.CharField(blank=True, help_text='Check <a\n            href=https://docs.clickup.com/en/articles/1367130-getting-started-with-the-clickup-api#personal-api-key>\n            how to find the personal API key</a>', max_length=255, verbose_name='Clickup personal API key'),
        ),
    ]
