# Generated by Django 3.2.5 on 2021-07-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickup_pk', models.CharField(blank=True, max_length=255)),
                ('google_auth_token', models.CharField(blank=True, editable=False, max_length=255)),
                ('google_auth_refresh_token', models.CharField(blank=True, editable=False, max_length=255)),
                ('google_auth_id_token', models.CharField(blank=True, editable=False, max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
