# Generated by Django 3.2.5 on 2021-08-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0003_remove_profile_google_auth_id_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
