# Generated by Django 3.2.5 on 2021-08-03 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sort_order_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarWebhook',
            fields=[
                ('calendar_id', models.CharField(max_length=256, unique=True)),
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(editable=False, max_length=256)),
                ('expiration', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(help_text="Google Calendar's calendar identifier", max_length=64)),
                ('list_id', models.CharField(help_text='Clickup list identifier', max_length=64)),
                ('tag_name', models.CharField(blank=True, help_text='Clickup tag name that will be added to matched events', max_length=64)),
                ('order', sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Order')),
                ('google_calendar_checked_at', models.DateTimeField(blank=True, help_text='Last time that the given calendar has been checked for\n            updated events', null=True)),
                ('google_calendar_webhook', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gcal2clickup.googlecalendarwebhook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username', 'order'),
                'unique_together': {('user', 'list_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncedEvent',
            fields=[
                ('task_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=64)),
                ('end_time', models.DateTimeField()),
                ('sync_description', models.BooleanField(null=True)),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcal2clickup.matcher')),
            ],
        ),
        migrations.CreateModel(
            name='ClickupWebhook',
            fields=[
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
