# Generated by Django 3.2.5 on 2021-08-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickupwebhook',
            name='clickup_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcal2clickup.clickupuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clickupwebhook',
            name='team_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
