# Generated by Django 3.2.5 on 2021-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcher',
            name='_description_regex',
            field=models.CharField(blank=True, help_text='Regular expression that will be used with the event description\n            in order to decide if a calendar event should be synced with a\n            clickup task', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='matcher',
            name='_name_regex',
            field=models.CharField(blank=True, help_text='Regular expression that will be used with the event name\n            in order to decide if a calendar event should be synced with a\n            clickup task', max_length=1024, null=True),
        ),
    ]
