# Generated by Django 3.2.5 on 2021-07-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
