# Generated by Django 3.2.5 on 2021-08-09 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickupWebhook',
            fields=[
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='clickupuser',
            name='webhook_id',
        ),
        migrations.AddField(
            model_name='clickupuser',
            name='id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
