# Generated by Django 3.2.5 on 2021-09-06 15:30

from django.db import migrations, models
import gcal2clickup.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0002_auto_20210810_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarwebhook',
            name='calendar_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='matcher',
            name='_description_regex',
            field=models.CharField(blank=True, help_text='Regular expression that will be used with the event description\n            in order to decide if a calendar event should be synced with a\n            clickup task', max_length=1024, null=True, validators=[gcal2clickup.validators.validate_is_pattern]),
        ),
        migrations.AlterField(
            model_name='matcher',
            name='_name_regex',
            field=models.CharField(blank=True, help_text='Regular expression that will be used with the event name\n            in order to decide if a calendar event should be synced with a\n            clickup task', max_length=1024, null=True, validators=[gcal2clickup.validators.validate_is_pattern]),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='sync_description',
            field=models.BooleanField(choices=[(None, 'No'), (True, 'Google Calendar -> Clickup'), (False, 'Clickup -> Google Calendar')], null=True),
        ),
    ]
