# Generated by Django 3.2.5 on 2021-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0002_auto_20210803_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matcher',
            name='calendar_id',
        ),
        migrations.RemoveField(
            model_name='matcher',
            name='google_calendar_checked_at',
        ),
        migrations.AddField(
            model_name='googlecalendarwebhook',
            name='checked_at',
            field=models.DateTimeField(editable=False, help_text='Last time that the given calendar has been checked for\n            updated events', null=True),
        ),
    ]
