# Generated by Django 3.2.5 on 2021-08-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0003_auto_20210804_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncedevent',
            old_name='end_time',
            new_name='end',
        ),
        migrations.AddField(
            model_name='syncedevent',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 8, 9, 3, 621915)),
            preserve_default=False,
        ),
    ]
