# Generated by Django 3.2.5 on 2021-09-09 16:43

from django.conf import settings
from django.db import migrations, models
import gcal2clickup.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcal2clickup', '0003_auto_20210906_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickupuser',
            name='token',
            field=models.CharField(blank=True, help_text='Check <a\n            href=https://docs.clickup.com/en/articles/1367130-getting-started-with-the-clickup-api#personal-api-key>\n            how to find the personal API key</a>', max_length=255, validators=[gcal2clickup.validators.validate_is_clickup_token], verbose_name='Clickup personal API key'),
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarwebhook',
            unique_together={('user', 'calendar_id')},
        ),
        migrations.AlterUniqueTogether(
            name='matcher',
            unique_together=set(),
        ),
    ]
