# Generated by Django 3.2.5 on 2021-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcal2clickup', '0004_auto_20210806_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matcher',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='matcher',
            name='_tags',
            field=models.CharField(blank=True, help_text='Clickup tag name that will be added to matched events.\n            One can add more than one tag by separating them with commas', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matcher',
            name='list_id',
            field=models.CharField(help_text='Clickup list.', max_length=64),
        ),
    ]
